### ISSUE TITLE
Speeding up Union, Intersection & Product

### ISSUE THREAD

**Issue by ruthhoffmann** [gap-packages/automata#15]
Currently the `UnionAutomata`, and `IntersectionAutomaton` functions spend a lot of their time turning the input automata into deterministic automata before computing the Union or Intersection automaton.
I believe skipping these steps will lead to an incredible speed up.

`ProductOfLanguages` has a similar slowdown when it starts with minimising the input automata. Again I believe skipping this step would enhance the function for large automata.

I have created such functions doing that for the `PatternClass` pkg 
[https://github.com/gap-packages/PatternClass/blob/master/lib/automata.gi](https://github.com/gap-packages/PatternClass/blob/master/lib/automata.gi)

**Comment by fingolfin** [comment]
@ManuelAFDelgado do you have any thoughts on this?

**Comment by ManuelAFDelgado** [comment]
Dear @fingolfin, dear @ruthhoffmann,
Thank you very much for pointing out this issue and, Ruth, for providing a patch.
I presume that I am the only author currently somehow taking care of the package (although just trying to keep the package running without any conflicts). Ruth, could you provide a pull request for this concrete case? And would you also like to become a maintainer and possibly make other improvements? (I do not know whether this makes sense or if there is something better one could do.)
Thanks again.

**Comment by ruthhoffmann** [comment]
I'd be happy to create a PR, can I just check if you have a preference on how to integrate the patch? Can I just replace the code for the functions as is? Or would you prefer alternative functions?

I would be happy to be a maintainer but please keep in mind that I have been so far very slow at maintaining my own package, but am trying to better myself at this! Not sure I have other improvements for the `automata` pkg, these were the main functions in `PatternClass` that slowed down the computation massively.

**Comment by ManuelAFDelgado** [comment]
Great! Replacing the code would be fine. I do not see any advantage in having alternative functions.
Since automata had fallen apart from my main research interests, I seldom made any improvements in the package. Thus, having you as a maintainer too will be great.

**Comment by ruthhoffmann** [comment]
Looking at the code, the ProductOfLanguages code was updated since I created the patch. What was the original bug? I wonder if my patch does not fix it.

**Comment by ManuelAFDelgado** [comment]
Thank you, Ruth.
The various occurrences of AlphabetOfAutomaton were replaced by AlphabetOfAutomatonAsList to fix a bug pointed out by Christian Sievers.
Please let me know if you prefer to fix your patch yourself or want me to do it.

**Comment by ruthhoffmann** [comment]
Thanks! Let me investigate what my patch for ProductOfLanguages is doing and fix it if something is off.

I will create a separate PR for it and would appreciate if you check it, in case I miss anything.

**Comment by ManuelAFDelgado** [comment]
@fingolfin, I can accept the pull request @ruthhoffmann created and then make a new release. In order to add @ruthhoffmann as a maintainer, does it suffice to make the appropriate change in PackageInfo?

**Comment by ruthhoffmann** [comment]
Excellent! Please don’t close the issue though.
I’m still messing around with ProductOfLanguages, which will have to be in its own PR.

Ruth 

>

**Comment by ruthhoffmann** [comment]
Let's close this issue as PR [16](https://github.com/gap-packages/automata/pull/16) addresses Union and Intersection. ProductOfLanguages needs checking, which I will do soon.
