### ISSUE TITLE
On rational expressions with more than 26-letter alphabets

### ISSUE THREAD

**Issue by Whitelisted2** [gap-packages/automata#17]
Based on the documentation (and online forums), the following is evident:
- GAP is able to construct random rational expressions with more than 26 characters, and is able to distinguish multi-letter characters in these generated expressions. (ex. a1, a2, etc. as units, as opposed to 'a','1', etc.) 
- If such expressions are defined using RationalExpression(), even using the optional parameter for specifying the alphabet, an error is thrown if this alphabet is not a string. Specifying such alphabets in strings is dicey, though.

Are there other ways to do this, or is GAP automata currently unable to handle this?

**Comment by ManuelAFDelgado** [comment]
Unfortunately, the package is unable to handle this. I'm sorry for not getting back to you sooner.
