### ISSUE TITLE
ProductOfLanguages returns bad automaton

### ISSUE THREAD

**Issue by chsievers** [gap-packages/automata#5]
The automaton returned as result of `ProductOfLanguages` doesn't correctly store its alphabet and returns to `AlphabetOfAutomatonAsList` what it should return to `AlphabetOfAutomaton`. As a consequence, `Display` and some further binary operations don't work:

```
gap> a:=ListOfWordsToAutomaton("ab",["a"]);;
gap> a2:=ProductOfLanguages(a,a);;
gap> AlphabetOfAutomatonAsList(a2);
2
gap> Display(a2);
Error, You cannot loop over the integer 2 did you mean the range [1..2] at ...

gap> ProductAutomaton(a2,a);
Error, A1 and A2 must have the same alphabet at ...
```

Replacing `AlphabetOfAutomaton` with `AlphabetOfAutomatonAsList` in line 791 of `aut-basics.gi` fixed that problem for me.
The other uses of `AlphabetOfAutomaton` in that file also seem dubious to me.

**Comment by ManuelAFDelgado** [comment]
Dear Christian,

You are right. I am very sorry for not having fixed this bug before. Your comment turned to fix the bug into an effortless task.

Thank you very much!
Manuel
